name: Ubuntu clang Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DBUILD_TOOLS=OFF
        -DBUILD_DEMO=OFF
        -DBUILD_TESTS=ON
        -DBUILD_LIB=ON
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror"
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config Release